FROM ubuntu:18.04

RUN apt-get update 
RUN apt-get install -y gcc g++ build-essential libssl-dev cmake wget unzip python3-dev git

ARG path=libtorch-cxx11-abi-shared-with-deps-1.8.1+cpu

RUN wget --no-check-certificate https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcpu.zip \
    && unzip ${path}.zip \
    && rm -r ${path}.zip

RUN git clone https://github.com/Abhiswain97/LibtorchDemo.git \
    && cd LibtorchDemo \
    && git checkout linux \
    && rm -r .gitignore .gitattributes README.md

WORKDIR /LibtorchDemo

RUN /bin/bash -c "apt install make && mkdir build"

WORKDIR /LibtorchDemo/build

RUN /bin/bash -c "cmake -DCMAKE_PREFIX_PATH=/libtorch .. && make"


