FROM ubuntu:18.04

RUN RUN apt-get update && apt-get install --no-install-recommends -y g++ cmake wget unzip python3-dev

ARG path=libtorch-cxx11-abi-shared-with-deps-1.8.1+cpu

RUN wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcpu.zip \
    && unzip ${path}.zip \
    && mkdir src

COPY LibtorchDemo.cpp CMakeLists.txt src/

WORKDIR /src/

RUN mkdir build \
    && cd build

RUN cmake -DCMAKE_PREFIX_PATH=~/${path}/libtorch/ .. \
    make \
    ./LibtorchDemo